omxvideodec: Workaround for Decoder initialized error
This patch is a workaround to avoid Decoder initialized error.
Phenomenon:
   - Sometimes error happens when running GStreamer :
     ERROR: from element /GstPipeline:pipeline0/GstOMXAACDec-omxaacdec:omxaacdec-omxaac
     Additional debug info:
     gstaudiodecoder.c(1798): gst_audio_decoder_chain (): /GstPipeline:pipeline0/GstOMX
     decoder not initialized
Cause:
   - Attempt to set unsupported color format to REL OMX component.
     The component supports only YUV 420 Semi Planar and Planar.

refs #57073
Signed-off-by: Thao Luong <thao.luong.uw@rvc.renesas.com>